### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by newhorizon-tech** [see-why/Best_Practise#2]
Good project. Just need to fix minor issues 

- Fix issues with "Edit task"
- Fix localstorage issues

**Comment by see-why** [comment]
Thanks a lot for noticing the bug in the code, turns out I had not run `npm run build` and pushed the `bunble.js` with the new changes in my javascript files.

I had done that with [this commit](https://github.com/see-why/Best_Practise/commit/c1fed05e0f60319c4dc10fc5b71ccf7b3057b5b6)...as such i have resolved the issue.
